# Generated by Django 5.0.7 on 2024-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_ipad'),
    ]

    operations = [
        migrations.CreateModel(
            name='iPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('imei_no1', models.CharField(max_length=50)),
                ('imei_no2', models.CharField(max_length=50)),
                ('mobile_status', models.CharField(max_length=50)),
                ('charger', models.BooleanField(default=False)),
                ('date_of_purchase', models.DateField()),
                ('purchased_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_details', models.CharField(max_length=255)),
                ('warranty_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
