# Generated by Django 5.0.7 on 2024-08-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_lanadapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_number', models.CharField(max_length=100)),
                ('sim_connection', models.CharField(max_length=100)),
                ('sim_status', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
