# Generated by Django 5.0.7 on 2024-08-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_sim'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('rental_laptop_brand', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram_capacity', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('inch', models.CharField(max_length=10)),
                ('laptop_status', models.CharField(max_length=50)),
                ('building_name', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
