# Generated by Django 5.0.7 on 2024-08-12 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_rentalasset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='exited',
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_officer',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('ram_capacity', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee')),
            ],
        ),
    ]
