# Generated by Django 5.0.7 on 2024-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_remove_employee_exited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email_id',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reporting_officer',
            field=models.CharField(max_length=100),
        ),
    ]
