# Generated by Django 5.0.7 on 2024-08-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_employee_exited_alter_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
