# Generated by Django 5.0.7 on 2024-08-19 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_employee_name_alter_employee_personal_email_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktop',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desktops', to='management.employee'),
        ),
        migrations.AddField(
            model_name='harddisk',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hard_disks', to='management.employee'),
        ),
        migrations.AddField(
            model_name='headset',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headsets', to='management.employee'),
        ),
        migrations.AddField(
            model_name='ipad',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipads', to='management.employee'),
        ),
        migrations.AddField(
            model_name='iphone',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iphones', to='management.employee'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyboards', to='management.employee'),
        ),
        migrations.AddField(
            model_name='keypadphone',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keypad_phones', to='management.employee'),
        ),
        migrations.AddField(
            model_name='lanadapter',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lan_adapters', to='management.employee'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laptops', to='management.employee'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mice', to='management.employee'),
        ),
        migrations.AddField(
            model_name='pendrive',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendrives', to='management.employee'),
        ),
        migrations.AddField(
            model_name='printer',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printers', to='management.employee'),
        ),
        migrations.AddField(
            model_name='rentalasset',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_assets', to='management.employee'),
        ),
        migrations.AddField(
            model_name='sim',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sims', to='management.employee'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smartphones', to='management.employee'),
        ),
    ]
