# Generated by Django 5.0.7 on 2024-08-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_desktop_employee_harddisk_employee_headset_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(choices=[('kannur', 'Kannur'), ('calicut', 'Calicut'), ('thrissur', 'Thrissur'), ('kochi', 'Kochi'), ('kottayam', 'Kottayam'), ('trivandrum', 'Trivandrum')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('FINANCE', 'FINANCE'), ('RM FINANCE', 'RM FINANCE'), ('RM', 'RM'), ('ACADAMICS', 'ACADAMICS'), ('CC', 'CC'), ('ONLINE OPERATIONS', 'ONLINE OPERATIONS'), ('ADMIN', 'ADMIN')], max_length=100),
        ),
    ]
