# Generated by Django 5.0.7 on 2024-10-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_employee_branch_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('purchase_date', models.DateField()),
                ('vendor', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash')], max_length=100)),
                ('payment_type', models.CharField(blank=True, choices=[('One Time Payment', 'One Time Payment'), ('Quarterly Payment', 'Quarterly Payment'), ('Half Yearly Payment', 'Half Yearly Payment'), ('Yearly Payment', 'Yearly Payment')], max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], max_length=100)),
                ('reference_transaction_id', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('next_payment_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
            ],
        ),
    ]
